The autograd package provides automatic differentiation for all operations on Tensors.

In [29]:
import torch

In [30]:
x = torch.ones(2,2,requires_grad = True)
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [31]:
z = y * y * 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


In [32]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [33]:
a = torch.randn(2,2)
print(a.requires_grad)
a.requires_grad_(True)

False


tensor([[-0.8131,  0.3677],
        [-0.6519, -0.3476]], requires_grad=True)

In [34]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([-196.9722,  701.5604,  808.5193], grad_fn=<MulBackward>)
tensor([ 51.2000, 512.0000,   0.0512])
